export const tourMeta = {"title": "The 2026 chapter", "checked": "2026-10-09", "scope": "2026 North American tour and festival appearances, plus the next announced show.", "source": "https://www.postmalone.com/shows/"};
export const stops = [
  {
    "date": "2026-04-10",
    "city": "Fort Lauderdale",
    "region": "Florida",
    "abbr": "FL",
    "country": "USA",
    "lat": 26.1224,
    "lon": -80.1373,
    "venue": "Tortuga Music Festival",
    "kind": "festival",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/New_York"
  },
  {
    "date": "2026-04-26",
    "city": "Indio",
    "region": "California",
    "abbr": "CA",
    "country": "USA",
    "lat": 33.7206,
    "lon": -116.2156,
    "venue": "Stagecoach Music Festival",
    "kind": "festival",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Los_Angeles"
  },
  {
    "date": "2026-05-16",
    "city": "Albuquerque",
    "region": "New Mexico",
    "abbr": "NM",
    "country": "USA",
    "lat": 35.0844,
    "lon": -106.6504,
    "venue": "Boots in the Park",
    "kind": "festival",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Denver"
  },
  {
    "date": "2026-05-31",
    "city": "Panama City Beach",
    "region": "Florida",
    "abbr": "FL",
    "country": "USA",
    "lat": 30.1766,
    "lon": -85.8055,
    "venue": "Gulf Coast Jam",
    "kind": "festival",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Chicago"
  },
  {
    "date": "2026-06-07",
    "city": "Myrtle Beach",
    "region": "South Carolina",
    "abbr": "SC",
    "country": "USA",
    "lat": 33.6891,
    "lon": -78.8867,
    "venue": "Carolina Country Music Fest",
    "kind": "festival",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/New_York"
  },
  {
    "date": "2026-06-09",
    "city": "Charlotte",
    "region": "North Carolina",
    "abbr": "NC",
    "country": "USA",
    "lat": 35.2271,
    "lon": -80.8431,
    "venue": "Bank of America Stadium",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/New_York"
  },
  {
    "date": "2026-06-12",
    "city": "Indianapolis",
    "region": "Indiana",
    "abbr": "IN",
    "country": "USA",
    "lat": 39.7684,
    "lon": -86.1581,
    "venue": "Lucas Oil Stadium",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/New_York"
  },
  {
    "date": "2026-06-16",
    "city": "Toronto",
    "region": "Ontario",
    "abbr": "ON",
    "country": "Canada",
    "lat": 43.6532,
    "lon": -79.3832,
    "venue": "Rogers Stadium",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Toronto"
  },
  {
    "date": "2026-06-20",
    "city": "Wildwood",
    "region": "New Jersey",
    "abbr": "NJ",
    "country": "USA",
    "lat": 38.9918,
    "lon": -74.8149,
    "venue": "Barefoot Country Music Fest",
    "kind": "festival",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/New_York"
  },
  {
    "date": "2026-06-22",
    "city": "East Hartford",
    "region": "Connecticut",
    "abbr": "CT",
    "country": "USA",
    "lat": 41.7823,
    "lon": -72.612,
    "venue": "Pratt & Whitney Stadium at Rentschler Field",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/New_York"
  },
  {
    "date": "2026-06-25",
    "city": "Cleveland",
    "region": "Ohio",
    "abbr": "OH",
    "country": "USA",
    "lat": 41.4993,
    "lon": -81.6944,
    "venue": "Huntington Bank Field",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/New_York"
  },
  {
    "date": "2026-06-27",
    "city": "Milwaukee",
    "region": "Wisconsin",
    "abbr": "WI",
    "country": "USA",
    "lat": 43.0389,
    "lon": -87.9065,
    "venue": "Summerfest",
    "kind": "festival",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Chicago"
  },
  {
    "date": "2026-06-30",
    "city": "Nashville",
    "region": "Tennessee",
    "abbr": "TN",
    "country": "USA",
    "lat": 36.1627,
    "lon": -86.7816,
    "venue": "Nissan Stadium",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Chicago"
  },
  {
    "date": "2026-07-02",
    "city": "Columbus",
    "region": "Ohio",
    "abbr": "OH",
    "country": "USA",
    "lat": 39.9612,
    "lon": -82.9988,
    "venue": "Historic Crew Stadium · Salute 250",
    "kind": "special",
    "source": "https://easyday.org/salute250/",
    "timeZone": "America/New_York"
  },
  {
    "date": "2026-07-08",
    "city": "Tampa",
    "region": "Florida",
    "abbr": "FL",
    "country": "USA",
    "lat": 27.9506,
    "lon": -82.4572,
    "venue": "Raymond James Stadium",
    "kind": "stadium",
    "source": "https://www.postmalone.com/gig/wednesday-july-8th-2026-raymond-james-stadium/",
    "timeZone": "America/New_York",
    "note": "Rescheduled from May 29."
  },
  {
    "date": "2026-07-11",
    "city": "Fayetteville",
    "region": "Arkansas",
    "abbr": "AR",
    "country": "USA",
    "lat": 36.0626,
    "lon": -94.1574,
    "venue": "Donald W. Reynolds Razorback Stadium",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Chicago"
  },
  {
    "date": "2026-07-15",
    "city": "Kansas City",
    "region": "Missouri",
    "abbr": "MO",
    "country": "USA",
    "lat": 39.0997,
    "lon": -94.5786,
    "venue": "Kauffman Stadium",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Chicago"
  },
  {
    "date": "2026-07-17",
    "city": "Ames",
    "region": "Iowa",
    "abbr": "IA",
    "country": "USA",
    "lat": 42.0308,
    "lon": -93.6319,
    "venue": "Jack Trice Stadium",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Chicago"
  },
  {
    "date": "2026-07-21",
    "city": "Missoula",
    "region": "Montana",
    "abbr": "MT",
    "country": "USA",
    "lat": 46.8721,
    "lon": -113.994,
    "venue": "Washington–Grizzly Stadium",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Denver"
  },
  {
    "date": "2026-07-24",
    "city": "Edmonton",
    "region": "Alberta",
    "abbr": "AB",
    "country": "Canada",
    "lat": 53.5461,
    "lon": -113.4938,
    "venue": "Commonwealth Stadium",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Edmonton"
  },
  {
    "date": "2026-07-25",
    "city": "Edmonton",
    "region": "Alberta",
    "abbr": "AB",
    "country": "Canada",
    "lat": 53.5461,
    "lon": -113.4938,
    "venue": "Commonwealth Stadium",
    "kind": "stadium",
    "source": "https://www.postmalone.com/gig/saturday-july-25th-2026-commonwealth-stadium/",
    "timeZone": "America/Edmonton"
  },
  {
    "date": "2026-07-28",
    "city": "Salt Lake City",
    "region": "Utah",
    "abbr": "UT",
    "country": "USA",
    "lat": 40.7608,
    "lon": -111.891,
    "venue": "Rice–Eccles Stadium",
    "kind": "stadium",
    "source": "https://news.livenationentertainment.com/news/post-malone-and-jelly-roll-present-the-big-ass-stadium-tour-part-2",
    "timeZone": "America/Denver"
  },
  {
    "date": "2026-08-29",
    "city": "Dieppe",
    "region": "New Brunswick",
    "abbr": "NB",
    "country": "Canada",
    "lat": 46.0789,
    "lon": -64.748,
    "venue": "MusiqArt Site · YQM Country Fest",
    "kind": "festival",
    "source": "https://www.setlist.fm/setlist/post-malone/2026/musiqart-site-dieppe-nb-canada-7341fa99.html",
    "timeZone": "America/Moncton"
  },
  {
    "date": "2026-10-24",
    "city": "Austin",
    "region": "Texas",
    "abbr": "TX",
    "country": "USA",
    "lat": 30.2672,
    "lon": -97.7431,
    "venue": "Circuit of the Americas · Formula 1 Grand Prix Weekend",
    "kind": "special",
    "source": "https://www.postmalone.com/",
    "timeZone": "America/Chicago"
  }
];
